/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportadora.view;

import dao.UsuarioData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Dell
 */
public class jifLogin extends javax.swing.JInternalFrame {

    private jfPrincipal root;
    private UsuarioData DAO;
    private Usuario usuario;

    public jifLogin(jfPrincipal f) {
        initComponents();
        root = f;
        try {
            DAO = new UsuarioData();
            usuario = new Usuario();
        } catch (Exception ex) {
            Logger.getLogger(jifLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbRegistrar = new javax.swing.JButton();
        jbEntrar = new javax.swing.JButton();
        jtApelido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Login");

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtApelido).addComponent(jLabel3).addComponent(jLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38,
                                        Short.MAX_VALUE)
                                .addComponent(jbEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpSenha))
                .addContainerGap(36, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(21, 21, 21).addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24).addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbRegistrarActionPerformed
        if (validarCampos()) {
            try {
                Usuario u = new Usuario();
                u.setApelido(jtApelido.getText());
                u.setSenha(String.valueOf(jpSenha.getPassword()));
                u = DAO.inserir(u);
                if (u.getId() > 0) {
                    usuario = u;
                    jfPrincipal frame = new jfPrincipal(usuario);
                    frame.setVisible(true);
                    root.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Registro não concluído", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Nome de usuário já existente", "Usuário não pôde ser registrado",
                        JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Registro não concluído",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_jbRegistrarActionPerformed

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbEntrarActionPerformed
        if (validarCampos()) {
            try {
                Usuario u = DAO.buscar(jtApelido.getText());
                if (u.getSenha().equals(String.valueOf(jpSenha.getPassword()))) {
                    usuario = u;
                    jfPrincipal frame = new jfPrincipal(usuario);
                    frame.setVisible(true);
                    root.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Senha incorreta", "Não autorizado", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(jifLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }// GEN-LAST:event_jbEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtApelido;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        if (jtApelido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o nome de usuário");
            jtApelido.requestFocus();
            return false;
        }
        if (jpSenha.getPassword().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a senha da conta");
            jpSenha.requestFocus();
            return false;
        }
        return true;
    }
}
